package cct_fx.entities;
// Generated Feb 25, 2016 4:18:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BankDetails generated by hbm2java
 */
public class BankDetails  implements java.io.Serializable {


     private int clientId;
     private PersonalDetails personalDetails;
     private Date startDate;
     private String accountType;
     private String accountName;
     private boolean hasBankStatement;
     private short numberOfAccounts;
     private long outstandingLoan;
     private String monthlyRepayment;

    public BankDetails() {
    }

    public BankDetails(PersonalDetails personalDetails, Date startDate, String accountType, String accountName, boolean hasBankStatement, short numberOfAccounts, long outstandingLoan, String monthlyRepayment) {
       this.personalDetails = personalDetails;
       this.startDate = startDate;
       this.accountType = accountType;
       this.accountName = accountName;
       this.hasBankStatement = hasBankStatement;
       this.numberOfAccounts = numberOfAccounts;
       this.outstandingLoan = outstandingLoan;
       this.monthlyRepayment = monthlyRepayment;
    }
   
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }
    public PersonalDetails getPersonalDetails() {
        return this.personalDetails;
    }
    
    public void setPersonalDetails(PersonalDetails personalDetails) {
        this.personalDetails = personalDetails;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public String getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }
    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }
    public boolean isHasBankStatement() {
        return this.hasBankStatement;
    }
    
    public void setHasBankStatement(boolean hasBankStatement) {
        this.hasBankStatement = hasBankStatement;
    }
    public short getNumberOfAccounts() {
        return this.numberOfAccounts;
    }
    
    public void setNumberOfAccounts(short numberOfAccounts) {
        this.numberOfAccounts = numberOfAccounts;
    }
    public long getOutstandingLoan() {
        return this.outstandingLoan;
    }
    
    public void setOutstandingLoan(long outstandingLoan) {
        this.outstandingLoan = outstandingLoan;
    }
    public String getMonthlyRepayment() {
        return this.monthlyRepayment;
    }
    
    public void setMonthlyRepayment(String monthlyRepayment) {
        this.monthlyRepayment = monthlyRepayment;
    }




}


