package cct_fx.entities;
// Generated Feb 25, 2016 4:18:34 PM by Hibernate Tools 4.3.1



/**
 * Commintments generated by hbm2java
 */
public class Commintments  implements java.io.Serializable {


     private int clientId;
     private PersonalDetails personalDetails;
     private String rents;
     private String loans;
     private String njangis;
     private String household;
     private String bills;
     private String mobilePhone;
     private String transport;
     private String others;

    public Commintments() {
    }

    public Commintments(PersonalDetails personalDetails, String rents, String loans, String njangis, String household, String bills, String mobilePhone, String transport, String others) {
       this.personalDetails = personalDetails;
       this.rents = rents;
       this.loans = loans;
       this.njangis = njangis;
       this.household = household;
       this.bills = bills;
       this.mobilePhone = mobilePhone;
       this.transport = transport;
       this.others = others;
    }
   
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }
    public PersonalDetails getPersonalDetails() {
        return this.personalDetails;
    }
    
    public void setPersonalDetails(PersonalDetails personalDetails) {
        this.personalDetails = personalDetails;
    }
    public String getRents() {
        return this.rents;
    }
    
    public void setRents(String rents) {
        this.rents = rents;
    }
    public String getLoans() {
        return this.loans;
    }
    
    public void setLoans(String loans) {
        this.loans = loans;
    }
    public String getNjangis() {
        return this.njangis;
    }
    
    public void setNjangis(String njangis) {
        this.njangis = njangis;
    }
    public String getHousehold() {
        return this.household;
    }
    
    public void setHousehold(String household) {
        this.household = household;
    }
    public String getBills() {
        return this.bills;
    }
    
    public void setBills(String bills) {
        this.bills = bills;
    }
    public String getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }
    public String getTransport() {
        return this.transport;
    }
    
    public void setTransport(String transport) {
        this.transport = transport;
    }
    public String getOthers() {
        return this.others;
    }
    
    public void setOthers(String others) {
        this.others = others;
    }




}


