package cct_fx.entities;
// Generated Feb 25, 2016 4:18:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EmploymentDetails generated by hbm2java
 */
public class EmploymentDetails  implements java.io.Serializable {


     private int clientId;
     private PersonalDetails personalDetails;
     private PreviousEmployment previousEmployment;
     private String occupation;
     private String employmentStatus;
     private String employerName;
     private String employerAddress;
     private Date employmentDate;
     private short paymentFrequency;
     private String paymentMode;
     private long minAnnualSalary;
     private boolean hasIncomeProof;

    public EmploymentDetails() {
    }

	
    public EmploymentDetails(PersonalDetails personalDetails, String occupation, String employmentStatus, String employerName, String employerAddress, Date employmentDate, short paymentFrequency, long minAnnualSalary, boolean hasIncomeProof) {
        this.personalDetails = personalDetails;
        this.occupation = occupation;
        this.employmentStatus = employmentStatus;
        this.employerName = employerName;
        this.employerAddress = employerAddress;
        this.employmentDate = employmentDate;
        this.paymentFrequency = paymentFrequency;
        this.minAnnualSalary = minAnnualSalary;
        this.hasIncomeProof = hasIncomeProof;
    }
    public EmploymentDetails(PersonalDetails personalDetails, PreviousEmployment previousEmployment, String occupation, String employmentStatus, String employerName, String employerAddress, Date employmentDate, short paymentFrequency, String paymentMode, long minAnnualSalary, boolean hasIncomeProof) {
       this.personalDetails = personalDetails;
       this.previousEmployment = previousEmployment;
       this.occupation = occupation;
       this.employmentStatus = employmentStatus;
       this.employerName = employerName;
       this.employerAddress = employerAddress;
       this.employmentDate = employmentDate;
       this.paymentFrequency = paymentFrequency;
       this.paymentMode = paymentMode;
       this.minAnnualSalary = minAnnualSalary;
       this.hasIncomeProof = hasIncomeProof;
    }
   
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }
    public PersonalDetails getPersonalDetails() {
        return this.personalDetails;
    }
    
    public void setPersonalDetails(PersonalDetails personalDetails) {
        this.personalDetails = personalDetails;
    }
    public PreviousEmployment getPreviousEmployment() {
        return this.previousEmployment;
    }
    
    public void setPreviousEmployment(PreviousEmployment previousEmployment) {
        this.previousEmployment = previousEmployment;
    }
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }
    public String getEmploymentStatus() {
        return this.employmentStatus;
    }
    
    public void setEmploymentStatus(String employmentStatus) {
        this.employmentStatus = employmentStatus;
    }
    public String getEmployerName() {
        return this.employerName;
    }
    
    public void setEmployerName(String employerName) {
        this.employerName = employerName;
    }
    public String getEmployerAddress() {
        return this.employerAddress;
    }
    
    public void setEmployerAddress(String employerAddress) {
        this.employerAddress = employerAddress;
    }
    public Date getEmploymentDate() {
        return this.employmentDate;
    }
    
    public void setEmploymentDate(Date employmentDate) {
        this.employmentDate = employmentDate;
    }
    public short getPaymentFrequency() {
        return this.paymentFrequency;
    }
    
    public void setPaymentFrequency(short paymentFrequency) {
        this.paymentFrequency = paymentFrequency;
    }
    public String getPaymentMode() {
        return this.paymentMode;
    }
    
    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode;
    }
    public long getMinAnnualSalary() {
        return this.minAnnualSalary;
    }
    
    public void setMinAnnualSalary(long minAnnualSalary) {
        this.minAnnualSalary = minAnnualSalary;
    }
    public boolean isHasIncomeProof() {
        return this.hasIncomeProof;
    }
    
    public void setHasIncomeProof(boolean hasIncomeProof) {
        this.hasIncomeProof = hasIncomeProof;
    }




}


