package cct_fx.entities;
// Generated Feb 25, 2016 4:18:34 PM by Hibernate Tools 4.3.1



/**
 * GuarrantorDetails generated by hbm2java
 */
public class GuarrantorDetails  implements java.io.Serializable {


     private Integer guarantorId;
     private PersonalDetails personalDetails;
     private String name;
     private String occupation;
     private String relationship;

    public GuarrantorDetails() {
    }

    public GuarrantorDetails(PersonalDetails personalDetails, String name, String occupation, String relationship) {
       this.personalDetails = personalDetails;
       this.name = name;
       this.occupation = occupation;
       this.relationship = relationship;
    }
   
    public Integer getGuarantorId() {
        return this.guarantorId;
    }
    
    public void setGuarantorId(Integer guarantorId) {
        this.guarantorId = guarantorId;
    }
    public PersonalDetails getPersonalDetails() {
        return this.personalDetails;
    }
    
    public void setPersonalDetails(PersonalDetails personalDetails) {
        this.personalDetails = personalDetails;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }
    public String getRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }




}


