package cct_fx.entities;
// Generated Feb 25, 2016 4:18:34 PM by Hibernate Tools 4.3.1



/**
 * MonthlyIncome generated by hbm2java
 */
public class MonthlyIncome  implements java.io.Serializable {


     private int clientId;
     private PersonalDetails personalDetails;
     private String monthlyIncome;
     private String otherIncome;

    public MonthlyIncome() {
    }

    public MonthlyIncome(PersonalDetails personalDetails, String monthlyIncome, String otherIncome) {
       this.personalDetails = personalDetails;
       this.monthlyIncome = monthlyIncome;
       this.otherIncome = otherIncome;
    }
   
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }
    public PersonalDetails getPersonalDetails() {
        return this.personalDetails;
    }
    
    public void setPersonalDetails(PersonalDetails personalDetails) {
        this.personalDetails = personalDetails;
    }
    public String getMonthlyIncome() {
        return this.monthlyIncome;
    }
    
    public void setMonthlyIncome(String monthlyIncome) {
        this.monthlyIncome = monthlyIncome;
    }
    public String getOtherIncome() {
        return this.otherIncome;
    }
    
    public void setOtherIncome(String otherIncome) {
        this.otherIncome = otherIncome;
    }




}


