package cct_fx.entities;
// Generated Feb 25, 2016 4:18:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PersonalDetails generated by hbm2java
 */
public class PersonalDetails  implements java.io.Serializable {


     private Integer clientId;
     private String firstName;
     private String lastName;
     private String address;
     private Date relocationDate;
     private String previousAddress;
     private String nationality;
     private long natIdNum;
     private long phoneNum;
     private Long phoneNum2;
     private String email;
     private String relationshipStatus;
     private Date birthDate;
     private short numberOfKids;
     private String educationLevel;
     private Commintments commintments;
     private EmploymentDetails employmentDetails;
     private AdditionalInfo additionalInfo;
     private BankDetails bankDetails;
     private Set guarrantorDetailses = new HashSet(0);
     private MonthlyIncome monthlyIncome;

    public PersonalDetails() {
    }

	
    public PersonalDetails(String firstName, String address, String nationality, long natIdNum, long phoneNum, String relationshipStatus, Date birthDate, short numberOfKids) {
        this.firstName = firstName;
        this.address = address;
        this.nationality = nationality;
        this.natIdNum = natIdNum;
        this.phoneNum = phoneNum;
        this.relationshipStatus = relationshipStatus;
        this.birthDate = birthDate;
        this.numberOfKids = numberOfKids;
    }
    public PersonalDetails(String firstName, String lastName, String address, Date relocationDate, String previousAddress, String nationality, long natIdNum, long phoneNum, Long phoneNum2, String email, String relationshipStatus, Date birthDate, short numberOfKids, String educationLevel, Commintments commintments, EmploymentDetails employmentDetails, AdditionalInfo additionalInfo, BankDetails bankDetails, Set guarrantorDetailses, MonthlyIncome monthlyIncome) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.relocationDate = relocationDate;
       this.previousAddress = previousAddress;
       this.nationality = nationality;
       this.natIdNum = natIdNum;
       this.phoneNum = phoneNum;
       this.phoneNum2 = phoneNum2;
       this.email = email;
       this.relationshipStatus = relationshipStatus;
       this.birthDate = birthDate;
       this.numberOfKids = numberOfKids;
       this.educationLevel = educationLevel;
       this.commintments = commintments;
       this.employmentDetails = employmentDetails;
       this.additionalInfo = additionalInfo;
       this.bankDetails = bankDetails;
       this.guarrantorDetailses = guarrantorDetailses;
       this.monthlyIncome = monthlyIncome;
    }
   
    public Integer getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getRelocationDate() {
        return this.relocationDate;
    }
    
    public void setRelocationDate(Date relocationDate) {
        this.relocationDate = relocationDate;
    }
    public String getPreviousAddress() {
        return this.previousAddress;
    }
    
    public void setPreviousAddress(String previousAddress) {
        this.previousAddress = previousAddress;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public long getNatIdNum() {
        return this.natIdNum;
    }
    
    public void setNatIdNum(long natIdNum) {
        this.natIdNum = natIdNum;
    }
    public long getPhoneNum() {
        return this.phoneNum;
    }
    
    public void setPhoneNum(long phoneNum) {
        this.phoneNum = phoneNum;
    }
    public Long getPhoneNum2() {
        return this.phoneNum2;
    }
    
    public void setPhoneNum2(Long phoneNum2) {
        this.phoneNum2 = phoneNum2;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRelationshipStatus() {
        return this.relationshipStatus;
    }
    
    public void setRelationshipStatus(String relationshipStatus) {
        this.relationshipStatus = relationshipStatus;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public short getNumberOfKids() {
        return this.numberOfKids;
    }
    
    public void setNumberOfKids(short numberOfKids) {
        this.numberOfKids = numberOfKids;
    }
    public String getEducationLevel() {
        return this.educationLevel;
    }
    
    public void setEducationLevel(String educationLevel) {
        this.educationLevel = educationLevel;
    }
    public Commintments getCommintments() {
        return this.commintments;
    }
    
    public void setCommintments(Commintments commintments) {
        this.commintments = commintments;
    }
    public EmploymentDetails getEmploymentDetails() {
        return this.employmentDetails;
    }
    
    public void setEmploymentDetails(EmploymentDetails employmentDetails) {
        this.employmentDetails = employmentDetails;
    }
    public AdditionalInfo getAdditionalInfo() {
        return this.additionalInfo;
    }
    
    public void setAdditionalInfo(AdditionalInfo additionalInfo) {
        this.additionalInfo = additionalInfo;
    }
    public BankDetails getBankDetails() {
        return this.bankDetails;
    }
    
    public void setBankDetails(BankDetails bankDetails) {
        this.bankDetails = bankDetails;
    }
    public Set getGuarrantorDetailses() {
        return this.guarrantorDetailses;
    }
    
    public void setGuarrantorDetailses(Set guarrantorDetailses) {
        this.guarrantorDetailses = guarrantorDetailses;
    }
    public MonthlyIncome getMonthlyIncome() {
        return this.monthlyIncome;
    }
    
    public void setMonthlyIncome(MonthlyIncome monthlyIncome) {
        this.monthlyIncome = monthlyIncome;
    }




}


