package cct_fx.entities;
// Generated Feb 25, 2016 4:18:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PreviousEmployment generated by hbm2java
 */
public class PreviousEmployment  implements java.io.Serializable {


     private int previousEmpId;
     private String employerName;
     private String employerAddress;
     private Date startDate;
     private Date endDate;
     private Set employmentDetailses = new HashSet(0);

    public PreviousEmployment() {
    }

	
    public PreviousEmployment(int previousEmpId, String employerName, String employerAddress, Date startDate, Date endDate) {
        this.previousEmpId = previousEmpId;
        this.employerName = employerName;
        this.employerAddress = employerAddress;
        this.startDate = startDate;
        this.endDate = endDate;
    }
    public PreviousEmployment(int previousEmpId, String employerName, String employerAddress, Date startDate, Date endDate, Set employmentDetailses) {
       this.previousEmpId = previousEmpId;
       this.employerName = employerName;
       this.employerAddress = employerAddress;
       this.startDate = startDate;
       this.endDate = endDate;
       this.employmentDetailses = employmentDetailses;
    }
   
    public int getPreviousEmpId() {
        return this.previousEmpId;
    }
    
    public void setPreviousEmpId(int previousEmpId) {
        this.previousEmpId = previousEmpId;
    }
    public String getEmployerName() {
        return this.employerName;
    }
    
    public void setEmployerName(String employerName) {
        this.employerName = employerName;
    }
    public String getEmployerAddress() {
        return this.employerAddress;
    }
    
    public void setEmployerAddress(String employerAddress) {
        this.employerAddress = employerAddress;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Set getEmploymentDetailses() {
        return this.employmentDetailses;
    }
    
    public void setEmploymentDetailses(Set employmentDetailses) {
        this.employmentDetailses = employmentDetailses;
    }




}


