package cct_fx.entities;
// Generated Feb 25, 2016 4:18:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Reference generated by hbm2java
 */
public class Reference  implements java.io.Serializable {


     private Integer referenceId;
     private String name;
     private String institution;
     private String position;
     private String phoneNum;
     private String email;
     private String referencecol;
     private Set additionalInfosForReferenceId2 = new HashSet(0);
     private Set additionalInfosForReferenceId3 = new HashSet(0);
     private Set additionalInfosForReferenceId1 = new HashSet(0);

    public Reference() {
    }

	
    public Reference(String name, String institution, String position) {
        this.name = name;
        this.institution = institution;
        this.position = position;
    }
    public Reference(String name, String institution, String position, String phoneNum, String email, String referencecol, Set additionalInfosForReferenceId2, Set additionalInfosForReferenceId3, Set additionalInfosForReferenceId1) {
       this.name = name;
       this.institution = institution;
       this.position = position;
       this.phoneNum = phoneNum;
       this.email = email;
       this.referencecol = referencecol;
       this.additionalInfosForReferenceId2 = additionalInfosForReferenceId2;
       this.additionalInfosForReferenceId3 = additionalInfosForReferenceId3;
       this.additionalInfosForReferenceId1 = additionalInfosForReferenceId1;
    }
   
    public Integer getReferenceId() {
        return this.referenceId;
    }
    
    public void setReferenceId(Integer referenceId) {
        this.referenceId = referenceId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(String institution) {
        this.institution = institution;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public String getPhoneNum() {
        return this.phoneNum;
    }
    
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getReferencecol() {
        return this.referencecol;
    }
    
    public void setReferencecol(String referencecol) {
        this.referencecol = referencecol;
    }
    public Set getAdditionalInfosForReferenceId2() {
        return this.additionalInfosForReferenceId2;
    }
    
    public void setAdditionalInfosForReferenceId2(Set additionalInfosForReferenceId2) {
        this.additionalInfosForReferenceId2 = additionalInfosForReferenceId2;
    }
    public Set getAdditionalInfosForReferenceId3() {
        return this.additionalInfosForReferenceId3;
    }
    
    public void setAdditionalInfosForReferenceId3(Set additionalInfosForReferenceId3) {
        this.additionalInfosForReferenceId3 = additionalInfosForReferenceId3;
    }
    public Set getAdditionalInfosForReferenceId1() {
        return this.additionalInfosForReferenceId1;
    }
    
    public void setAdditionalInfosForReferenceId1(Set additionalInfosForReferenceId1) {
        this.additionalInfosForReferenceId1 = additionalInfosForReferenceId1;
    }




}


